project_id = "jnbdhtlmdxtanwlubyis"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-invitation]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.generate-daily-tasks]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-clinic-setup-email]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false